version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
  php:
    build: ./docker/php
    ports: ['9000:9001']
    volumes:
      - ./magento:/var/www/magento:cached
    links:
      - mysql
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./magento:/var/www/magento:cached
